version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7-ram
    environment:
      - DB_CONNECTION: circle_testing
      - DB_DATABASE circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout

      - run:
          name: setup
          command: |
              sudo apt update && sudo apt install -y mariadb-client libpng-dev libjpeg-dev zlib1g-dev
              sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include
              sudo docker-php-ext-install zip pdo_mysql gd
              sudo composer self-update

      #composerキャッシュ検索
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      #composerライブラリインストール
      - run: composer install -n --prefer-dist

      #composerキャッシュ生成
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      #npmキャッシュ検索
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-

      #npmライブラリインストール
      - run: npm install

      #npmキャッシュ生成
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      #PHPUnit実行
      - run: ./vendor/bin/phpunit